[package]
name = "indiana"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
hashbrown = {version = "0.15.2",  features = ["serde"]}
serde = {version = "1.0.217", features = ["derive"]}
toml = "0.8.19"
