name: Build Debian Package

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build Debian package
        run: cargo deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: target/debian/*.deb
