name: Build for Windows

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true

      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: target/x86_64-pc-windows-gnu/release/mole.exe
